#kubectl run  n1 --image=nginx --port=80 
#kubectl expose POD n1 --port=80 --target-port=80  --name=n1s --type=LoadBalancer
#kubectl apply -f nginx.yml

apiVersion: v1
kind: Namespace
metadata:
  name: dev
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: n1
#   namespace: dev
# spec:
#   containers:
#   - name: n1
#     image: nginx
#     ports:
#     - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    env: dev
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: n1
      labels:
        app: nginx
        env: dev
    spec:
      containers:
      - name: nginx 
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: n1s
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 